(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Descartes Theorem


BeginPackage["DescartesFunctions`"]


Unprotect["`*"];ClearAll["`*"];
(*unprotect and clear out old definitionsn-allows repeated loading and alterations*)


DescartesFunctions::usage="This package is where all the descartes thereoms functions are stored.";


DescartesTheorem::usage="calculates the inner circle that fit between three tangent circles";


DescartesTheoremNeg::usage="calculates the outer circle that fit between three tangent circles";


Begin["`Private`"]


Simplify[Solve[(2((1/a)^2+(1/b)^2+(1/c)^2+(1/d)^2))==(1/a+1/b+1/c+1/d)^2,d]];


DescartesTheorem[a_,b_,c_]:=(a b c (b c+a (b+c)-2 Sqrt[a] Sqrt[b] Sqrt[c] Sqrt[a+b+c]))/(a^2 (b-c)^2+b^2 c^2-2 a b c (b+c))


DescartesTheoremNeg[a_,b_,c_]:=(a b c (b c+a (b+c)+2 Sqrt[a] Sqrt[b] Sqrt[c] Sqrt[a+b+c]))/(a^2 (b-c)^2+b^2 c^2-2 a b c (b+c))


End[]


Protect[Evaluate[$Context<>"*"]];


EndPackage[]
