(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Moving Functions


Needs["SmallFunctions`"]


BeginPackage["MovingFunctions`"]


Unprotect["`*"];ClearAll["`*"];
(*unprotect and clear out old definitionsn-allows repeated loading and alterations*)


MovingFunctions::usage="This package is where all the movement maipulation and calculating functions are stored.";


MoveNewBubble::usage="calculated the distance a new bubble has to move from its nearest neighbours";


Begin["`Private`"]


MoveNewBubble[fp_, dt_, bubbleList_,precisionFactor_]:=
Module[{centList,radii,fk,dist1,dist3,post1,moveM},
centList= Map[First,bubbleList];
radii = Map[Function[dummy,dummy[[2]]],bubbleList];
radii=Map[SmallFunctions`MyaveFn, radii];
moveM=(((dt+radii[[1]]))*((fp-centList[[1]])/SmallFunctions`DistancebtwPoints[centList[[1]],fp]));
fk={centList[[1]],centList[[1]]}+{moveM,-moveM};
fk[[1]]=SmallFunctions`TomakeDistanceExact[bubbleList[[1]],{fk[[1]],dt},(radii[[1]]+dt),precisionFactor,2][[2]];
fk[[2]]=SmallFunctions`TomakeDistanceExact[bubbleList[[1]],{fk[[2]],dt},(radii[[1]]+dt),precisionFactor,2][[2]];
dist1=Map[Function[dummy1,
Map[Function[dummy,
SmallFunctions`DistancebtwPoints[dummy,dummy1]],
fk]],
centList];
dist3=Flatten[Apply[Plus, dist1]];
post1=Flatten[Position[dist3,Min[dist3]]];
fk[[post1[[1]]]]
]


End[]


Protect[Evaluate[$Context<>"*"]];


EndPackage[]
